ksqldb_cli_container: ksqldb-cli
ksqldb_server_url: http://ksqldb-server:8088
queries:
  - gmv_daily_finance_performance.sql
  - gross_profit_daily_finance_performance.sql
  - outcome_daily_finance_performance.sql
  - uss_daily_finance_performance.sql
  - net_profit_daily_finance_performance.sql
  - revenue_daily_finanance_performance.sql
  - daily_finance_performance.sql
